missing_adjectives = {
    'famous': 4,
    'forgettable': -4,
    'uninspired': -4,
    'monotonous': -4,
    'exemplary': 4,
    'legendary': 4,
    'exceptional': 4,
    'incredible': 4,
    'sumptuous': 4,
    'seminal': 4,
    'unlistenable': -4,
    'tremendous': 4,
    'memorable': 3,
    'evocative': 3,
    'infectious': 3,
    'predictable': -3,
    'inventive': 3,
    'dramatic': 3,
    'derivative': -3,
    'essential': 3,
    'incendiary': 3,
    'monstrous': -3,
    'mellifluous': 3,
    'pretentious': -3,
    'ponderous': -3,
    'extraordinary': 3,
    'unimaginative': -3,
    'fatuous': -3,
    'mawkish': -3,
    'classic': 2,
    'considerable': 2,
    'atmospheric': 2,
    'notable': 2,
    'exotic': 2,
    'soulful': 2,
    'wanna-be': -2,
    'pedestrian': -2,
    'sloppy': -2,
    'ingenious': 2,
    'well-crafted': 2,
    'commercial': -1,
    'lyrical': 1,
    'major': 1,
    'spiritual': 1,
    'stylistic': 1,
    'corporate': -1,
    'danceable': 1,
    'radical': 1,
    'golden': 1,
    'definitive': 1,
    'understated': 1,
    'ordinary': -1,
    'unable': -1,
    'poppy': 1,
    'physical': 1,
    'cinematic': 1,
    'crucial': 1,
    'sing-along': 1,
    'raucous': 1,
    'anthemic': 1,
    'poetic': 1,
    'multi-layered': 1,
    'listenable': 1,
    'well-worn': -1,
    'acoustic': 0.5,
    'hot': 0.5,
    'orchestral': 0.5,
    'simplistic': -0.5,
    'self-conscious': -0.5,
    'emotive': 0.5,
    'able': 0.2,
    'contemporary': 0.2,
    'usual': -0.1,
    'modern': -0.1,
    'average': -0.1,
    'similar': -0.1,
    'consistent': 0.1,
    'laconic': 0.1,
}

updates_to_vader_values = {
    'melancholy': 2,
}

other_missing_words = {
    'fantastically': 1,
}